"""Initial tables with all features

Revision ID: 5d77a1ea9ff2
Revises: 
Create Date: 2025-11-11 19:32:54.011811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d77a1ea9ff2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('status', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_devices_id'), 'devices', ['id'], unique=False)


    op.create_table('batteries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('voltage', sa.Integer(), nullable=False),
                    sa.Column('capacity', sa.Integer(), nullable=False),
                    sa.Column('lifetime', sa.Integer(), nullable=False),
                    sa.Column('device_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_index(op.f('ix_batteries_id'), 'batteries', ['id'], unique=False)
    # ### end Alembic commands ###

    op.execute("""
        CREATE OR REPLACE FUNCTION check_battery_limit()
        RETURNS TRIGGER AS $$
        BEGIN
            IF NEW.device_id IS NOT NULL THEN
                IF (SELECT COUNT(*) FROM batteries WHERE device_id = NEW.device_id) >= 5 THEN
                    RAISE EXCEPTION 'Cannot have more than 5 batteries per device';
                END IF;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER battery_limit_trigger
            BEFORE INSERT OR UPDATE ON batteries
            FOR EACH ROW
            EXECUTE FUNCTION check_battery_limit();
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP TRIGGER IF EXISTS battery_limit_trigger ON batteries")
    op.execute("DROP FUNCTION IF EXISTS check_battery_limit")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batteries_id'), table_name='batteries')
    op.drop_table('batteries')
    op.drop_index(op.f('ix_devices_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###